# This is a weird way of telling Travis to use the fast container-based test
# runner instead of the slow VM-based runner.
sudo: false

language: go

go:
  - "1.9.x"
  - "1.10.x"
  - master

install: make dep

script: make build check test
